#ifndef MANIKIN_BLE_PROTOCOL_DEFINITIONS
#define MANIKIN_BLE_PROTOCOL_DEFINITIONS

#include <zephyr/kernel.h>

#define MANIKIN_BLE_CRC_SEED 0x0000U

/*
 * Given the message structure:
 * | START | LENGTH | SOF_MSG | CMD | MSG | EOF_MSG | CRC | STOP |
 *
 * These defines specify the contants START, SOF_MSG, EOF_MSG and STOP
 */
#define MANIKIN_BLE_PACKET_START_BYTE 0x01U
#define MANIKIN_BLE_PACKET_SOF_MSG    0x3AU
#define MANIKIN_BLE_PACKET_EOF_MSG    0x3BU
#define MANIKIN_BLE_PACKET_STOP_BYTE  0x17U

/* Positions in message frame */
#define MANIKIN_BLE_START_BYTE_POS      0U
#define MANIKIN_BLE_LENGTH_BYTE_POS     1U
#define MANIKIN_BLE_SOF_MSG_POS         2U
#define MANIKIN_BLE_CMD_POS             3U
#define MANIKIN_BLE_PAYLOAD_POS         4U
#define MANIKIN_BLE_EOF_MSG_POS(LEN)    (MANIKIN_BLE_PAYLOAD_POS + LEN)
#define MANIKIN_BLE_CRC_POS(LEN)        (MANIKIN_BLE_PAYLOAD_POS + LEN + 1U)
#define MANIKIN_BLE_STOP_BYTE_POS(LEN)  (MANIKIN_BLE_EOF_MSG_POS(LEN) + 3U)
#define MANIKIN_BLE_PACKET_MINIMAL_SIZE 7U

#define MANIKIN_BLE_ATT_MTU (CONFIG_MANIKIN_BLE_MAX_ATT_SIZE - MANIKIN_BLE_PACKET_MINIMAL_SIZE)

#define MANIKIN_BLE_BUFFER_SPACE (CONFIG_MANIKIN_BLE_MAX_TEMPORARY_BUFFER_SIZE * CONFIG_MANIKIN_BLE_MAX_BUFFERS)

typedef enum
{
    MANIKIN_BLE_IS_RESP      = 1U,
    MANIKIN_BLE_CMD_ANY      = 2U,
    MANIKIN_BLE_CMD_START    = 4U,
    MANIKIN_BLE_CMD_STOP     = 8U,
    MANIKIN_BLE_CMD_DATA     = 16U,
    MANIKIN_BLE_CMD_TIMEDATA = 32U,
    MANIKIN_BLE_CMD_INVALID  = 64U
} manikin_ble_cmd_t;

typedef struct {
    manikin_ble_cmd_t command;
    struct k_sem sem;
} manikin_ble_subscription_t;

#endif /* BLE_GATT_PROTOCOL_DEFINITIONS */